version: "3.11"

services:
   redis:
      image: redis:7-alpine
      restart: always
      env_file: .env
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:/redis_data

   db_migrations:
      build: .
      restart: on-failure
      env_file: .env
      command: sh -c "python -m alembic upgrade head"

   bot:
      build: .
      restart: always
      env_file: .env
      ports:
        - 9500:9500
      volumes:
        - ./bot:/app/bot
        - ./migrations:/app/migrations
        - ./utils:/app/utils
        - ./db.sqlite3:/app/db.sqlite3
      depends_on:
         - redis
         - db_migrations

volumes:
   redis-data:
